### PR TITLE
iOS integration

### PR DESCRIPTION
**Pull request by durul**

### CODE REVIEW

**Comment by khaled-0** [comment]
You just ran ``flutter create --platform=ios`` 

I am not adding ios support because I don't have an iOS device to build/test app right now.

So unfortunately, I don't think this PR will work out for now. Thanks for your time though.

**Comment by durul** [comment]
> You just ran `flutter create --platform=ios`
> 
> I am not adding ios support because I don't have an iOS device to build/test app right now.
> 
> So unfortunately, I don't think this PR will work out for now. Thanks for your time though.

Simulator Screen Recording - iPhone 16 - 2024-11-10 at 11 26 38

**Comment by khaled-0** [comment]
It's good to see that everything "probably" works.
However there's some extra ios related setups for some dependencies. Could you please also look into those.
e.g the launcher icons/native splash/notification/media playback etc.
Also remove the placeholder test as I have yet to implement unit tests.

**Comment by durul** [comment]
> It's good to see that everything "probably" works. However, there are some extra iOS-related setups for some dependencies. Could you please also look into those, e.g., the launcher icons/native splash/notification/media playback, etc.? Also, remove the placeholder test, as I have yet to implement unit tests.
> 
> And then there's the ci/cd

✅ remove the placeholder test, as I have yet to implement unit tests.
✅ Ci/Cd conflict fixed

I looked at the dependencies, but I couldn't see any extra ones. Also, some assets were added automatically for iOS by the Flutter generator.

Can you please point out specific concerns about which dependencies and setups?

**Comment by khaled-0** [comment]
hey, I think we're ready to merge this 
before that could you please add launcher icons and native splash in the corresponding files used by android.
I'll take care of the ci/cd afterwards

**Comment by khaled-0** [comment]
btw also try this using AltStore 
https://nightly.link/khaled-0/TubeSync/actions/runs/11821248584/tubesync_ios_nightly.zip
need to confirm CI works

**Comment by khaled-0** [comment]
implemented in #17

**Pull request closed without merging**
