### PR TITLE
Fix AlertDialog Layout Issue in import_playlist_dialog.dart

### PR DESCRIPTION
**Pull request by durul**

### CODE REVIEW

**Comment by khaled-0** [comment]
please add description as to what this pr does and how does it improve / fix existing code

**Comment by durul** [comment]
> please add description as to what this pr does and how does it improve / fix existing code


## Issue Description
A rendering exception is occurring in the `AlertDialog` component due to improper layout sizing of a `RenderPhysicalShape` widget. The widget attempts to paint before its dimensions are properly calculated, causing a layout failure.

**Error Message:**
[error_log.txt](https://github.com/user-attachments/files/17692114/error_log.txt)

RenderBox was not laid out: RenderPhysicalShape#f9904 relayoutBoundary=up2
Failed assertion: line 2164 pos 12: 'hasSize'

This occurs when Flutter tries to paint a widget that hasn't been adequately laid out yet. Looking at the error message, it's happening in an AlertDialog in your import_playlist_dialog.dart file in Android Pixel4. 

## Additional Notes
This fix addresses the layout assertion error that was preventing the AlertDialog from rendering properly. The changes ensure that all widgets in the component tree have proper size constraints before the paint phase.

**Comment by khaled-0** [comment]
LGTM. btw did you AI generate the message

**Comment by durul** [comment]
> LGTM. btw did you AI generate the message

yes I did

**Pull request merged**
